
//WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM D:\Insurgent\tools\shader_compiler.exe

#ifndef _SHADERS_INCLUDED
#define _SHADERS_INCLUDED

#define SHADER_ENTRY_VERTEX "vertexFunc"
#define SHADER_ENTRY_FRAGMENT "fragmentFunc"
#define SHADER_ENTRY_COMPUTE "computeFunc"

#ifdef INCLUDE_SHADERS_INETERNAL
typedef struct {
	u64 code_offset;
	u64 code_size;
	u32 stage;
} ShaderInfo;

const ShaderInfo c_shader_infos[] = {
	(ShaderInfo) {
		.stage = VK_SHADER_STAGE_COMPUTE_BIT,
		.code_offset = 0,
		.code_size = 732,
	},
	(ShaderInfo) {
		.stage = VK_SHADER_STAGE_FRAGMENT_BIT,
		.code_offset = 732,
		.code_size = 384,
	},
	(ShaderInfo) {
		.stage = VK_SHADER_STAGE_VERTEX_BIT,
		.code_offset = 1116,
		.code_size = 1824,
	},
};

#define SHADER_COUNT 3
#define SHADER_BUFFER_SIZE 2940LU
#endif
#define SHADER_ID_DISTRIBUTION_C 0
#define SHADER_ID_TRIANGLE_F 1
#define SHADER_ID_TRIANGLE_V 2

#endif

