
//WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM D:\Insurgent\tools\shader_compiler.exe

#ifndef _SHADERS_INCLUDED
#define _SHADERS_INCLUDED

typedef struct {
	u64 code_offset;
	u64 code_size;
	u32 stage;
} ShaderInfo;

#define SHADER_ENTRY_VERTEX "vertexFunc"
#define SHADER_ENTRY_FRAGMENT "fragmentFunc"
#define SHADER_ENTRY_COMPUTE "computeFunc"

const ShaderInfo c_shader_infos[] = {
	(ShaderInfo) {
		.stage = VK_SHADER_STAGE_FRAGMENT_BIT,
		.code_offset = 0,
		.code_size = 384,
	},
	(ShaderInfo) {
		.stage = VK_SHADER_STAGE_VERTEX_BIT,
		.code_offset = 384,
		.code_size = 1472,
	},
};

#define SHADER_ID_TRIANGLE_F 0
#define SHADER_ID_TRIANGLE_V 1
#define SHADER_COUNT 2
#define SHADER_BUFFER_SIZE 1856LU

#endif

